spring:
  datasource:
    url: jdbc:h2:mem:ftms_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/mp_ftms_test
  cache:
    type: simple
app:
  demo:
    seed-enabled: false

